### PR TITLE
Bugfix `sparse_mul!` handling of `beta`

### LINKED ISSUE #17: [BUG] Wrong answer in `sparse_mul!`
Currently, the code for `sparse_mul!` contains a small error. Whenever there are multiple entries contributing to a single output, the `beta` parameter will in fact be used that many times.

https://github.com/ITensor/SparseArraysBase.jl/blob/aceca8ce00164c503a0866710f7506d02d4d0ff0/src/abstractsparsearrayinterface.jl#L352

MWE
```julia
using SparseArraysBase: SparseArrayDOK
a = SparseArrayDOK{Float64}(2, 2)
for I in eachindex(a)
    a[I] = 1
end
```
```julia
julia> a
2×2 SparseMatrixDOK{Float64, typeof(SparseArraysBase.default_getunstoredindex)}:
 1.0  1.0
 1.0  1.0

julia> a * a
2×2 SparseMatrixDOK{Float64, typeof(SparseArraysBase.default_getunstoredindex)}:
 1.0  1.0
 1.0  1.0

julia> Array(a) * Array(a)
2×2 Matrix{Float64}:
 2.0  2.0
 2.0  2.0
```

### PR DESCRIPTION
**Pull request by lkdvos**
This fixes #17 using the method discussed there, which pre-multiplies the output storage with `beta`.

Some questions I had, which relate to some design choices:
- If we are not assuming that the unstored values are zeros, I cannot "empty" the destination storage, even with `beta = 0`. As a result, the current implementation will not discard stored zeros. Maybe we want a mechanism to be able to control that?
- I looked into using `map_stored!`, but it was unclear to me whether using `a_dest` both as input and output is something that is allowed by the API. I know the `Base.map!` has a warning for this, and so we should probably decide whether the API supports that or not.

### CODE REVIEW

File: test/basics/test_linalg.jl [hunk 1]
```diff
@@ -0,0 +1,35 @@
+using SparseArraysBase: SparseArrayDOK
+using LinearAlgebra: mul!
+using Random
```
Comment (mtfishman) [inline test/basics/test_linalg.jl:3]:
```suggestion
using Random: rand
```
Also probably we should set a seed, and use https://github.com/JuliaRandom/StableRNGs.jl to make sure the results are reproducible.

File: src/abstractsparsearrayinterface.jl [hunk 2]
```diff
@@ -357,11 +357,13 @@ function sparse_mul!(
   β::Number=false;
   (mul!!)=(default_mul!!),
 )
+  storage(a_dest) .*= β
```
Comment (mtfishman) [inline src/abstractsparsearrayinterface.jl:360]:
```suggestion
  a_dest .*= β
```
Does this work? It should check that the broadcast call preserves the zero values and then just broadcast over the nonzero/stored values.

I'm ok using some "lower level" functionality like this if needed, but my goal was to try to make sure high level abstractions works in a smart way.

Also, an issue is that `storage` isn't part of the general API, and is really an implementation detail of `SparseArrayDOK`, so I think it should be `storedvalues(a_dest) .*= β`, if `a_dest .*= β` doesn't work for some reason.

File: src/abstractsparsearrayinterface.jl [hunk 3]
```diff
@@ -357,11 +357,13 @@ function sparse_mul!(
...
+  β′ = true
```
Comment (mtfishman) [inline src/abstractsparsearrayinterface.jl:361]:
```suggestion
  β′ = one(Bool)
```
I know I used `true` and `false` other places, but I think we should switch over to this style, since it shows the intent of the code better. I remember the first time I saw `true` and `false` used as unopinionated one and zero values I was very confused, but I couldn't think of a better alternative. At some point Miles suggested the style `one(Bool)` and `zero(Bool)` as an alternative, which I think is more readable.

File: test/basics/test_linalg.jl [hunk 4]
```diff
@@ -0,0 +1,35 @@
...
+
+# TODO: add this to main package
```
Comment (mtfishman) [inline test/basics/test_linalg.jl:5]: Good idea, though as I'm sure you know we should make it more general, i.e. allow specifying the axes or size and allow passing an RNG.

Comment (lkdvos) [reply test/basics/test_linalg.jl:8]: Haha indeed, this is why I didn't add it immediately. 😄  I'll get to it soon, just want to keep the PRs clean so they have a single topic, making it a lot easier to review and the git history is better

**Comment by mtfishman** [comment]
>     * If we are not assuming that the unstored values are zeros, I cannot "empty" the destination storage, even with `beta = 0`. As a result, the current implementation will not discard stored zeros. Maybe we want a mechanism to be able to control that?

It's a good question about whether we are assuming unstored values are zeros or not, and maybe that is not handled in a consistent way right now. Even though you _can_ customize `getunstoredindex` to output values other than zero, a lot of code still assumes the unstored value is some kind of zero (either numerical zero or a zero array). Probably we should formalize that a bit better and make it clear what operations make that assumption. Maybe it even warrants having different kinds of sparse arrays, where `SparseArrayDOK` does assume the unstored values are zeros, and then we can have a `GenericSparseArrayDOK` that doesn't make that assumption. My thinking on that was basically that as long as we are clear on what functions assume unstored values are zeros, it is "buyer beware" and you are free to construct `SparseArrayDOK` with other unstored values but some operations like matrix multiplication won't make sense (if you have something like an array of strings, algebra operations like matrix multiplication don't make much sense anyway).

In terms of emptying the destination storage, I actually thought that was working, but I guess not:
```julia
julia> using SparseArraysBase

julia> a = SparseArrayDOK{Float64}(2, 2)
2×2 SparseMatrixDOK{Float64, typeof(SparseArraysBase.default_getunstoredindex)}:
 ⋅  ⋅
 ⋅  ⋅

julia> a[1, 1] = 1
1

julia> a .*= 0
2×2 SparseMatrixDOK{Float64, typeof(SparseArraysBase.default_getunstoredindex)}:
 0.0  ⋅
  ⋅   ⋅

julia> a[1, 1] = 1
1

julia> map!(Returns(0), a, a)
2×2 SparseMatrixDOK{Float64, typeof(SparseArraysBase.default_getunstoredindex)}:
 0.0  ⋅
  ⋅   ⋅

julia> a[1, 1] = 1
1

julia> fill!(a, 0)
2×2 SparseMatrixDOK{Float64, typeof(SparseArraysBase.default_getunstoredindex)}:
 0.0  ⋅
  ⋅   ⋅

julia> a[1, 1] = 1
1
```
The only one that works is:
```julia
julia> SparseArraysBase.zero!(a)
2×2 SparseMatrixDOK{Float64, typeof(SparseArraysBase.default_getunstoredindex)}:
 ⋅  ⋅
 ⋅  ⋅
```
At some point I thought I had a codepath in fill, map, and broadcast that checked if it is filling with zero and in that case it would call `SparseArraysBase.zero!` but maybe that got removed during one of the refactors.

>     * I looked into using `map_stored!`, but it was unclear to me whether using `a_dest` both as input and output is something that is allowed by the API. I know the `Base.map!` has a warning for this, and so we should probably decide whether the API supports that or not.

Good question, I didn't think too much about aliasing in the map operations. More broadly, we should discuss what we want the API to be for operating on just the stored values, in general I have been trying to push that down to an implementation detail so that higher level code and users don't have to think about that, since that can go wrong pretty easily. But maybe it would be good to make `map_stored!` "more official", or users should use things like `map!(x -> 2x, storedvalues(a), storedvalues(a))` or `storedvalues(a) .*= 2`, assuming the aliasing is handled properly.

File: src/abstractsparsearrayinterface.jl (hunk 2 above)
Comment (lkdvos) [reply src/abstractsparsearrayinterface.jl]: So `a_dest .*= beta` does not work (and actually just outputs wrong results in general). I'll open an issue:
```julia
julia> a
2×2 SparseMatrixDOK{Float64, typeof(SparseArraysBase.default_getunstoredindex)}:
 1.0  ⋅
  ⋅   ⋅

julia> a .*= 2
2×2 SparseMatrixDOK{Float64, typeof(SparseArraysBase.default_getunstoredindex)}:
 0.0  ⋅
  ⋅   ⋅
```

File: src/abstractsparsearrayinterface.jl (hunk 3 above)
Comment (mtfishman) [reply src/abstractsparsearrayinterface.jl:361]: Thanks for the reminder, I was vaguely aware of some funny business like that, that is some pretty crazy behavior... Agreed it makes more sense to have specialized one and zero types for this kind of thing.

File: src/abstractsparsearrayinterface.jl (hunk 2 above)
Comment (mtfishman) [reply src/abstractsparsearrayinterface.jl]: Oh, yikes, that's a bad bug! Maybe something funny going on with the logic that is checking if the function preserves zero values, that part isn't so easy to get right...

File: src/abstractsparsearrayinterface.jl (hunk 3 above)
Comment (mtfishman) [reply src/abstractsparsearrayinterface.jl:361]: (You resolved the conversation but I didn't see it changed to `β′ = one(Bool)`.)

Comment (lkdvos) [reply src/abstractsparsearrayinterface.jl]: Apologies, I did not mean to do that. Should now be resolved

File: src/abstractsparsearrayinterface.jl [hunk 5]
```diff
@@ -357,11 +357,13 @@ function sparse_mul!(
   β::Number=false;
   (mul!!)=(default_mul!!),
 )
+  storedvalues(a_dest) .*= β
```
Comment (mtfishman) [inline src/abstractsparsearrayinterface.jl:360]:
```suggestion
  # TODO: Change to: `a_dest .*= β`
  # once #19 is fixed.
  storedvalues(a_dest) .*= β
```

File: src/abstractsparsearrayinterface.jl [hunk 6]
```diff
@@ -357,11 +357,15 @@ function sparse_mul!(
   β::Number=false;
   (mul!!)=(default_mul!!),
 )
+  # TODO: Change to: `a_dest .*= β`
+  # once #19 is fixed.
```
Comment (mtfishman) [inline src/abstractsparsearrayinterface.jl:361]:
```suggestion
  # once https://github.com/ITensor/SparseArraysBase.jl/issues/19 is fixed.
```

**Comment by mtfishman** [comment]
@lkdvos looks good to me, I added a comment reminding us to change that line once #19 is fixed.

Can you bump the version? After that I'll merge.

**Review by mtfishman — APPROVED** [review]
