### PR TITLE
Fix issues with in-place map/broadcast

### LINKED ISSUE #19: [BUG] Broadcasting assignments are not working
MWE:

```julia
using SparseArraysBase
a = SparseArraysBase.SparseArrayDOK{Float64}(2,2)
a[1] = 1
```

```julia
julia> a
2×2 SparseMatrixDOK{Float64, typeof(SparseArraysBase.default_getunstoredindex)}:
 1.0  ⋅
  ⋅   ⋅

julia> a .*= 2
2×2 SparseMatrixDOK{Float64, typeof(SparseArraysBase.default_getunstoredindex)}:
 0.0  ⋅
  ⋅   ⋅
```

### PR DESCRIPTION
**Pull request by mtfishman**
Fixes #19, though I need to add tests before merging.

@lkdvos does this unaliasing logic look right to you? The tricky cases for me to think about are when the source and destination are overlapping slices of the same sparse array, I have some tests that check this logic works to fix both #19 and those cases but I can't tell if it is either being too conservative, or not conservative enough in some situation I haven't been able to devise...

### CODE REVIEW

File: src/abstractsparsearrayinterface.jl [hunk 1]
```diff
@@ -261,19 +269,18 @@ end
...
+  # to make sure the inputs aren't overwritten incorrectly.
+  # See: https://github.com/JuliaLang/julia/blob/v1.11.2/base/broadcast.jl#L935-L948
+  as = map(a -> a_dest === a ? a : Base.unalias(a_dest, a), as)
+  indices_stored = eachstoredindex(as...)
+  if eachstoredindex(a_dest) ⊈ indices_stored
+    # If not all indices being mapped over are stored in the destination,
+    # zero out the destination. An extreme example of this is when
+    # the sources are sparse but the destination is dense.
+    @interface interface zero!(a_dest)
+  end
```
Comment (lkdvos) [inline src/abstractsparsearrayinterface.jl:282]: I'm not entirely convinced the branch is worth it. If I'm not mistaken, checking the subset is ``O(nnz)``, which means that checking that not all indices are being mapped over takes a considerable amount of time. I would think that a default implementation should simply zero out the resulting memory unconditionally, and a specific type might have a different implementation if they have more information. It's a bit hard to reason about a good default implementation for "any sparse storage", so I would prefer conservative fallbacks that are guaranteed to work.
If you think that this check is worth it though, perhaps it could be worth it to try to refactor that logic into a separate function, which can be specialized to alter the behavior

**Review by lkdvos — COMMENTED** [review]
I think the unaliasing logic makes sense, although it might be sensible to have a special code path for specific cases where `map!(f, a, a)` is being called, since there you would probably simply loop `a[i] = f(a[i])` without having to worry about zeroing out the storage.

This being said, looking at the code a bit more, I think this still is not handling `zeropreserving` and `nonzeropreserving` functions very well either right? Probably we should open an issue for that, since I would say that silent wrong results are way worse than throwing errors

**Comment by mtfishman** [comment]
> I think the unaliasing logic makes sense, although it might be sensible to have a special code path for specific cases where `map!(f, a, a)` is being called, since there you would probably simply loop `a[i] = f(a[i])` without having to worry about zeroing out the storage.

I tried refactoring the code taking this and your comment about when to call `zero!` into account, please take a look.

> This being said, looking at the code a bit more, I think this still is not handling `zeropreserving` and `nonzeropreserving` functions very well either right? Probably we should open an issue for that, since I would say that silent wrong results are way worse than throwing errors

I think the logic right now is correct and safe but maybe not necessarily efficient, since it relies on allocating a prototypical unstored element and checking it is zero which may involve allocating a big array, in the case of sparse arrays of arrays.

**Review by lkdvos — APPROVED** [review]
